Made sure HTTP timeout is longer than router-config timeout
rutebanken/OpenTripPlanner pull request #15
Opened 2017-08-21 12:39 UTC by gmellemstrand

2017-08-21 13:14 UTC, seime commented on src/main/java/org/opentripplanner/index/IndexAPI.java
> +        int final_timeout = ChecktimeOut(timeout);
Use java conventions for naming of variables and methods

2017-08-21 13:14 UTC, seime commented on src/main/java/org/opentripplanner/index/IndexAPI.java
> +        if (router.timeouts.length > 0 && (router.timeouts[0] + 1) * 2000 > timeout) {
IMHO the timeout should be larger than the sum of router timouts

2017-08-21 13:14 UTC, seime commented on src/main/java/org/opentripplanner/index/IndexAPI.java
> +        int final_timeout = ChecktimeOut(timeout);
Timeout should only be altered if NOT specified in the http header (only modify timeouts for requests NOT specifying the OTPTimeout header)

2017-08-30 06:05 UTC, seime requested changes
Adhere to Java code standards, not .NET.

Squash all commits into single commit with rich comment

2017-08-30 11:21 UTC, seime commented on src/main/java/org/opentripplanner/index/IndexAPI.java
> +    private int CheckTimeout(int timeout) {
Still wrong case on method

2017-08-30 12:10 UTC, gmellemstrand commented
Should be ok now

2017-08-30 13:01 UTC, seime requested changes
Does it compile?

2017-08-31 08:55 UTC, gmellemstrand commented
It compiles now

2017-08-31 09:18 UTC, merged